#
# Xiaomi Common Touchscreen Feature
#

obj-$(CONFIG_TOUCHSCREEN_XIAOMI_COMMON)                += lct_tp_info.o
obj-$(CONFIG_TOUCHSCREEN_XIAOMI_COMMON)                += lct_tp_selftest.o
obj-$(CONFIG_TOUCHSCREEN_XIAOMI_COMMON)                += lct_tp_gesture.o
obj-$(CONFIG_TOUCHSCREEN_XIAOMI_COMMON)                += lct_tp_grip_area.o
obj-$(CONFIG_TOUCHSCREEN_XIAOMI_COMMON)                += lct_tp_work.o
obj-$(CONFIG_TOUCHSCREEN_XIAOMI_COMMON)                += lct_tp_palm.o
obj-$(CONFIG_TOUCHSCREEN_XIAOMI_COMMON)                += aaabbb/